server:
  port: 9093
---
spring:
  # DB DataSource ??
  datasource:
    # h2
    url: jdbc:h2:tcp://localhost/~/test
    driverClassName: org.h2.Driver
    username: sa
    password:

  # h2(in Memory RDBMS) ??
  h2:
    console:
      enabled: true